[phases.setup]
nixPkgs = ["python3", "wget"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "bash bin/download_weights"
]

[start]
cmd = "gunicorn --config gunicorn_config.py api_server_production:app"

