[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "wget"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade || true",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "bash bin/download_weights"
]

[start]
cmd = "gunicorn --config gunicorn_config.py api_server_production:app"

