services:
  - type: web
    name: object-detection-api
    env: python
    buildCommand: pip install -r requirements_api.txt
    startCommand: gunicorn --config gunicorn_config.py api_server_production:app
    envVars:
      - key: PORT
        value: 5000

